game_screen_x_start = 0
game_screen_y_start = 15
screen_x_size = 10
screen_y_size = 20
game_tick_ms = 50
snake_before_head_str = "D"
snake_head = "X"
apple_icon = "A"
start_text = "Snake Game! Press any key to start"
end_text =  "Game OVER, Apples eaten:"
point_text = "Points: "
speed_up_sound = "audio/div5.wav"
eat_sound = "audio/eat.wav"
game_over_sound = "audio/gameover.wav"